editors:
  execs: [1, 2]
  content: [3, 4]
  design: [5, 6]
  graphics: [7, 8]
  copy: [9, 10]
  pub-soc: [11, 23, 24, 12, 13]
  distro: [14, 15]
  web: [22]
  business: [16]
  relatives: [17, 18, 21]
  muir: [19]
